export const currency = '$';
export const currentYear = new Date().getFullYear();
export const appName = 'STRATOPOD';
export const appTitle = 'STRATOPOD - Dashboard';
export const appDescription = 'STRATOPOD Dashboard';
export const author = 'Stratopod';
export const authorWebsite = '';
export const authorContact = '';
export const basePath = '';